### ISSUE TITLE
filecmp not found

### ISSUE THREAD

**Issue by snelle-jelle** [pycom/pycom-libraries#101]
Hi,

In the OTA example server side. The LoPy 4 can't find import filecmp

LoPy 4 version: 1.18.2r7

Do I have to add the file / module somewhere. I can't find previouse problems with it.

**Comment by iwahdan88** [comment]
Hi @snelle-jelle , I think you mean OTA example , in that case the LoPy4 does not act as Server in the OTA process , LoPy4 is the client.

**Comment by snelle-jelle** [comment]
Okay, I thought the server side was also running on another LoPy in the example. I will try that then. Thanks!

EDIT: changed it to OTA.
