### ISSUE TITLE
LoRaWAN Nanogateway for AS923

### ISSUE THREAD

**Issue by sh4nnongoh** [pycom/pycom-libraries#11]
Hi,

Is there a working example for interaction with the Things Network using AS923?

I have 2 LoPys with each acting as an OTAA node and a nano gateway node respectively.
I modified the following files as follows,

config.py:
```
SERVER = 'router.as.thethings.network'
LORA_FREQUENCY = 923200000 
LORA_DR = "SF10BW125" 
```

nanogateway.py:
```
RX_PK = {"rxpk": [{"time": "", "tmst": 0,
                   "chan": 2, "rfch": 0,
                   "freq": 923.2, "stat": 1,
                   "modu": "LORA", "datr": "SF10BW125",
                   "codr": "4/5", "rssi": 0,
                   "lsnr": 0, "size": 0,
                   "data": ""}]}
```

OTAA/main.py:
```
for channel in range(0, 72):
    lora.remove_channel(channel)

for i in range(0, 16):
    lora.add_channel(i, frequency=923200000, dr_min=0, dr_max=4) #not sure why cannot set DR5
```

The JOIN_REQUEST & JOIN_ACCEPT messages have been successfully generated. However, my OTAA node is unable to join the network.

![image](https://cloud.githubusercontent.com/assets/13437033/26526680/f0168646-43b4-11e7-948c-817f612cc245.png)

Please advise, thank you.

**Comment by Bucknalla** [comment]
Hi @sh4nnongoh could you please share your OTAA node, code?

Thanks!

**Comment by sdaniel55** [comment]
Hi @sh4nnongoh, I'll close this issue due to inactivity. If you're still having problems, feel free to reopen it. Thanks!
