### ISSUE TITLE
Pyscan MFRC630.py: mfrc630_iso14443a_select(uid) returns 4 byte UID on 7 byte card

### ISSUE THREAD

**Issue by AstarothPoD** [pycom/pycom-libraries#120]
When I use the example code from Pyscan, replacing MFRC630.mpy with MFRC630.py (mpy file not working) I get wrong UID length on any 7 byte UID length cards, it always returns 4 byte UID.

**Comment by Xykon** [comment]
Sorry it took a while to fix this but updated libraries are now available. Please let me know if you continue to have issues.

**Comment by johnrcassidy** [comment]
Was this ever resolved and the appropriate .py file included in the library?  I get the same errors as @AstarothPoD even when following #123
