### ISSUE TITLE
What happened to pytrack.py?

### ISSUE THREAD

**Issue by danalvarez** [pycom/pycom-libraries#135]
Hello,

Trying to use a Pytrack 1.0, most examples import the library via `from pytrack import Pytrack`. However, all links point to this repo: https://github.com/pycom/pycom-libraries/blob/master/pytrack, **which no longer exists**. Where can I find the correct library to import?

Best,

Dan

**Comment by peter-pycom** [comment]
Ah, yes, that has been restructured recently. The files are here now: https://github.com/pycom/pycom-libraries/tree/master/shields

And the update to the documentation has been merged just now. So, now there shouldn't be any more broken links flying around. If you spot any more broken links, please do let us know!
