### ISSUE TITLE
PyTrack and PySense

### ISSUE THREAD

**Issue by deblasioluca** [pycom/pycom-libraries#153]
Dear all

I'm trying to execute example accelerometer_wake, but I'm missing the library PyTrack and / or PySense. In various posts there was the reference to a folder "pycom-libraries-master" but I can't find this. Where can I download the both libraries?

Thank you for your help

Regards
Luca

**Comment by gijsio** [comment]
Please check here: https://github.com/pycom/pycom-libraries/releases/tag/v2.0.0 for the complete examples. You can unzip the folder and it will contain the respective projects ready to upload
