### ISSUE TITLE
valueError : 868100000

### ISSUE THREAD

**Issue by frankdunn** [pycom/pycom-libraries#31]
Hi

I get ValueError 868100000 on startup but nanogateway is connecting to ttn . If I change value LORA_FREQUENCY = 903900000 there is no error .

**Comment by danicampora** [comment]
That's because your LoPy is programmed with the 915MHz firmware.

**Comment by frankdunn** [comment]
Thank you

Do I need to build firmware or can I use the pycom firmware updater to
install new firmware ?

**Comment by sdaniel55** [comment]
Hi @frankdunn, you can read how to update the firmware [here](https://docs.pycom.io/chapter/gettingstarted/installation/firmwaretool.html). I'll close this issue for now, feel free to reopen it if you're still having issues
