### ISSUE TITLE
Pysense // LIS2HH12 // no yaw()

### ISSUE THREAD

**Issue by rpcme** [pycom/pycom-libraries#37]
File

pycom-libraries/pysense/main.py

calls method yaw() but yaw() does not exist in

pycom-libraries/pysense/lib/LIS2HH12.py

it seems to have been removed by commit f05ce07458c16a49d62b4e8646e7afeede9a816c but the sample application main.py was not updated.

**Comment by danicampora** [comment]
Fixed here: https://github.com/pycom/pycom-libraries/commit/f1c0cd9be175d8a61f9737b54fb2c8f3acadca39

Thanks!
