### ISSUE TITLE
MQTT Sock Has no Attribute

### ISSUE THREAD

**Issue by pinxau1000** [pycom/pycom-libraries#49]
ERROR OUTPUT:
```
File "/flash/lib/mqtt.py", line 94 in ping
AttributeError: 'NoneType' object has no attribute 'write'
```

This error happens everytime a sock object is calls a function like on sock.ping() or on sock.write().

Someone knows how to fix this ?

Best Regards

**Comment by pinxau1000** [comment]
My bad, I forgot the `client.connect()`
:'(

**Comment by niallp** [comment]
This could be closed ?

**Comment by sdaniel55** [comment]
Hi @pinxau1000, I think this issue has been resolved, so I'll close this. If you think otherwise, feel free to reopen it and add more details
