### ISSUE TITLE
MQTT set_last_will

### ISSUE THREAD

**Issue by FranciscoGJ** [pycom/pycom-libraries#58]
hi!, how can i use wills in mqtt. Can you give me an example?

**Comment by chrisvoo** [comment]
Hi Francisco,
I don't have an example, but probably you should just call set_last_will passing a topic and a message as parameters in that order, [like shown in the signature of the method](https://github.com/micropython/micropython-lib/blob/master/umqtt.simple/umqtt/simple.py#L47).
This should be called before `connect` method.
See also [this thread in the micropython forum](https://forum.micropython.org/viewtopic.php?t=3584).

**Comment by FranciscoGJ** [comment]
wow! thanks, I had not set the  keepalive params, that was my problem.

**Comment by sdaniel55** [comment]
Hi @FranciscoGJ, I think this issue has been resolved, so I'll close this. If you think otherwise, feel free to reopen it and add more details. Thanks!
