### ISSUE TITLE
SQN3330 firmware updater OSError: AT+SMSWBOOT=3,0 failed!

### ISSUE THREAD

**Issue by simonpfeifhofer** [pycom/pycom-libraries#59]
Got the following error updating SQN3330 firmware:

```
<<< Welcome to the SQN3330 firmware updater >>>
Entering recovery mode
Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "/flash/lib/sqnsupgrade.py", line 126, in run
OSError: AT+SMSWBOOT=3,0 failed!
MicroPython v1.8.6-849-56d00234 on 2018-05-18; GPy with ESP32
```

**Comment by mikolajo** [comment]
I have the same issue, have you found any solution?

**Comment by tmcolby** [comment]
I also cannot seem to get the firmware to update.  I am using the uartmirror method.

>>> sqnsupgrade.run('/home/tyson/pycom/FIPY_GPY_CATM1_33988.dup', 921600, port='/dev/ttyUSB0')
<<< Welcome to the SQN3330 firmware updater >>>
Entering recovery mode
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tyson/pycom/pycom-libraries/lib/sqnsupgrade/sqnsupgrade.py", line 126, in run
    raise OSError('AT+SMSWBOOT=3,0 failed!')
OSError: AT+SMSWBOOT=3,0 failed!

**Comment by mikolajo** [comment]
so for me worked: putting the run segment into looped try, after couple iterations it got it right

**Comment by sdaniel55** [comment]
Hi @simonpfeifhofer, did you manage to update the firmware? If not, please reopen this issue and I can help you with it.

**Comment by sh4nnongoh** [comment]
Hi @sdaniel55 , I have problems with this detailed here.

https://forum.pycom.io/topic/3547/fipy-lte-nb-problems-sqn3330-firmware-updater

Is it really true that I need to update the LTE-M1 first before LTE-NB?

**Comment by sdaniel55** [comment]
Hi @sh4nnongoh, I've replied to your post on the forum, so I'll just post it here too

> "Please check [this](https://forum.pycom.io/topic/3549/important-update-regarding-lte-modem-updates) post for updates about the modem upgrades. Hope this helps!"
