### ISSUE TITLE
MQTT error ECONNRESET

### ISSUE THREAD

**Issue by robmarkcole** [pycom/pycom-libraries#87]
Hi I am receiving the following error after 2 packets are published successfully, with source code [here](https://github.com/robmarkcole/pycom-projects/blob/master/PMS5003%20air%20quality%20sensor/main.py):
```
>>> client.publish("wipy/", "test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/flash/lib/mqtt.py", line 110, in publish
OSError: [Errno 104] ECONNRESET
```
This error is [reported](https://forum.pycom.io/topic/3648/umqtt-robust-stalls-out-on-fipy) in a couple of different threads on the forums, and [perhaps can be resolved](https://forum.pycom.io/topic/2311/mqtt-oserror-issue/3) by implementing umqtt-robust. I don't get this error when publishing from my Mac.

UPDATE: I identified the root cause as my using the same `client_id` on multiple devices.

**Comment by sdaniel55** [comment]
Hi @robmarkcole 👋 Can I close this ticket then?

**Comment by robmarkcole** [comment]
HI @sdaniel55 if the error cannot be handled to provide more debugging info, then yes please close. However I could have saved 1 hr with some more debugging info and I'm sure i won't be the last to get this  error. Therefore if it could be handeld better perhaps this can be a feature request?
Cheers
Robin

**Comment by sdaniel55** [comment]
@robmarkcole I'll mark it as a feature request then 😉 Do you have anything else to add? There's a [feature request template](https://github.com/pycom/pycom-libraries/issues/new?template=feature_request.md) for issues, if you need some guidance.

**Comment by robmarkcole** [comment]
To define the feature request: more informative messages on errors, thanks :-)
